#!/usr/bin/env python3
"""Generate 30 lexicon term .md files (5 existing + 25 new)."""
import os

TERMS = [
    # === AI Decision Operations (5) ===
    {
        "slug": "the-fluent-fallacy",
        "name": "The Fluent Fallacy",
        "pos": "n.",
        "definition": "The belief that a clear AI answer is a correct AI answer.",
        "category": "ai-decision-operations",
        "explanation": "AI systems can sound confident even when they are wrong. The risk is not only bad information. The risk is bad information entering decisions without friction.",
        "example": "A manager asks an AI tool to summarize incident trends. The answer sounds complete, but the model misses missing data, old definitions, and unresolved edge cases. The team acts on a polished answer, not a verified signal.",
        "why_it_matters": "Fluent answers reduce skepticism. In risk operations, that can turn small errors into bad decisions.",
        "teams_get_wrong": "They treat AI confidence as accuracy. They skip verification because the output looks right.",
        "strong_teams": "Use AI for acceleration, not verification. Require source checks, owner review, and clear escalation rules before action.",
        "related_terms": ["ai-theater", "model-worship", "automation-fog"],
        "keywords": ["AI accuracy", "AI confidence", "AI decision risk"],
    },
    {
        "slug": "ai-theater",
        "name": "AI Theater",
        "pos": "n.",
        "definition": "The organizational performance of adopting AI without changing operations.",
        "category": "ai-decision-operations",
        "explanation": "Companies announce AI initiatives, hire AI teams, and build demos — but never change how decisions are made, who owns escalation, or how signals reach action. The AI exists for optics, not outcomes.",
        "example": "A retail company deploys a fraud detection model. It fires alerts into a shared inbox. Nobody is assigned to act on them. The model works. The organization does not.",
        "why_it_matters": "AI Theater wastes budget, erodes trust in AI, and delays real operational improvement by creating the illusion that progress is happening.",
        "teams_get_wrong": "They measure AI success by deployment count, not decision improvement.",
        "strong_teams": "Define the operating model change before building the AI. Measure decisions improved, not models shipped.",
        "related_terms": ["the-fluent-fallacy", "dashboard-sedation", "governance-fog"],
        "keywords": ["AI transformation failure", "fake AI adoption", "AI washing"],
    },
    {
        "slug": "escalation-debt",
        "name": "Escalation Debt",
        "pos": "n.",
        "definition": "The accumulated cost of signals that were detected but never acted on.",
        "category": "ai-decision-operations",
        "explanation": "Every time a risk signal fires and nobody escalates, the organization accumulates escalation debt. The debt compounds until a crisis forces payment.",
        "example": "A fraud team detects a pattern three weeks before it becomes a major loss event. The analyst flags it in a report. The report goes to a manager who will discuss it next week. The loss hits.",
        "why_it_matters": "Escalation debt is invisible until it is catastrophic. It is the gap between detection capability and decision authority.",
        "teams_get_wrong": "They invest in better detection without fixing the escalation path. More signals, same inaction.",
        "strong_teams": "Pre-commit decision rights. Define who acts, under what conditions, within what time — before the signal arrives.",
        "related_terms": ["dashboard-sedation", "the-fluent-fallacy", "decision-latency"],
        "keywords": ["escalation failure", "risk signal ignored", "decision latency"],
    },
    {
        "slug": "governance-fog",
        "name": "Governance Fog",
        "pos": "n.",
        "definition": "When AI governance committees create the appearance of oversight without enabling action.",
        "category": "ai-decision-operations",
        "explanation": "Monthly committee meetings discuss AI risks. They request more analysis. Nothing gets deployed. Meanwhile, ungoverned AI usage spreads through shadow tools.",
        "example": "A bank forms an AI Ethics Board. It meets quarterly. It has no authority to approve or block deployments. Teams deploy anyway without telling the board.",
        "why_it_matters": "Governance fog gives leadership false comfort while real AI risk goes unmanaged.",
        "teams_get_wrong": "They build governance for documentation, not for decisions.",
        "strong_teams": "Governance sets boundaries and guardrails. Teams operate freely within them. No approval needed for pre-approved patterns.",
        "related_terms": ["ai-theater", "escalation-debt", "the-fluent-fallacy"],
        "keywords": ["AI governance failure", "AI committee", "AI oversight"],
    },
    {
        "slug": "decision-latency",
        "name": "Decision Latency",
        "pos": "n.",
        "definition": "The time between detecting a problem and having authority to act on it.",
        "category": "ai-decision-operations",
        "explanation": "AI detects in milliseconds. Humans approve in days. The gap between detection speed and decision speed is where losses accumulate.",
        "example": "An anomaly detection system flags suspicious activity at 2am. The on-call analyst sees it but cannot block the account without manager approval. The manager responds at 9am. Seven hours of exposure.",
        "why_it_matters": "Every minute of decision latency is a minute of uncontrolled risk. In fraud, that is money. In security, that is data.",
        "teams_get_wrong": "They optimize model accuracy while ignoring the approval chain that follows the alert.",
        "strong_teams": "Measure time-to-action, not just time-to-detection. Pre-authorize responses for known patterns.",
        "related_terms": ["escalation-debt", "governance-fog", "ai-theater"],
        "keywords": ["decision speed", "approval chain", "response time"],
    },
    # === Dashboard Failure (5) ===
    {
        "slug": "dashboard-sedation",
        "name": "Dashboard Sedation",
        "pos": "n.",
        "definition": "The calming effect of seeing green metrics while the operation is failing.",
        "category": "dashboard-failure",
        "explanation": "Dashboards create a feeling of control. Green numbers feel like safety. But when thresholds are too loose or metrics lag reality, the dashboard becomes a sedative, not a signal.",
        "example": "A logistics team reviews their on-time delivery dashboard every morning. It shows 94 percent — above target. But the target was set two years ago, competitors are at 98 percent, and failures concentrate in highest-value accounts.",
        "why_it_matters": "Sedated teams do not escalate. They do not question. They report green and move on — until the problem is too large to ignore.",
        "teams_get_wrong": "They trust the dashboard without questioning the thresholds, the lag, or the missing context.",
        "strong_teams": "Review thresholds quarterly. Ask what would make this dashboard lie to us. Test by removing it for a week.",
        "related_terms": ["metric-theater", "the-fluent-fallacy", "vanity-signal"],
        "keywords": ["dashboard problems", "false confidence metrics", "green dashboard failure"],
    },
    {
        "slug": "metric-theater",
        "name": "Metric Theater",
        "pos": "n.",
        "definition": "Presenting metrics that look impressive but drive no operational decisions.",
        "category": "dashboard-failure",
        "explanation": "Teams build elaborate dashboards for leadership reviews. The numbers are real. The impact is zero. Nobody changes behavior based on what the dashboard shows.",
        "example": "A BI team presents 40 slides of year-over-year trends. Leadership nods. The meeting ends. No action items. No thresholds. No owners. The same deck runs next quarter with updated numbers.",
        "why_it_matters": "Metric theater consumes analyst time that could produce intelligence. It trains leadership to treat data as decoration.",
        "teams_get_wrong": "They optimize for presentation quality instead of decision utility.",
        "strong_teams": "Every metric has an owner, a threshold, and a pre-defined action. If a metric cannot trigger a decision, it gets removed.",
        "related_terms": ["dashboard-sedation", "vanity-signal", "reporting-addiction"],
        "keywords": ["vanity metrics", "KPI theater", "useless dashboards"],
    },
    {
        "slug": "vanity-signal",
        "name": "Vanity Signal",
        "pos": "n.",
        "definition": "A metric that makes the team look good without connecting to operational outcomes.",
        "category": "dashboard-failure",
        "explanation": "Vanity signals are chosen because they trend upward, not because they matter. They survive because nobody asks what decision this metric drives.",
        "example": "A marketing team reports 200 percent increase in page views. Revenue is flat. The page views come from bot traffic and internal testing. Nobody checks.",
        "why_it_matters": "Vanity signals consume attention that should go to actionable intelligence. They create false confidence in leadership.",
        "teams_get_wrong": "They celebrate the metric without connecting it to a business outcome.",
        "strong_teams": "For every metric, ask: if this number doubled tomorrow, what would we do differently? If the answer is nothing, remove it.",
        "related_terms": ["metric-theater", "dashboard-sedation", "reporting-addiction"],
        "keywords": ["vanity metrics", "meaningless KPIs", "metric manipulation"],
    },
    {
        "slug": "reporting-addiction",
        "name": "Reporting Addiction",
        "pos": "n.",
        "definition": "The organizational habit of producing more reports instead of making more decisions.",
        "category": "dashboard-failure",
        "explanation": "When something goes wrong, the response is another report. When leadership wants visibility, the response is another dashboard. The organization becomes addicted to documenting problems instead of solving them.",
        "example": "After a major incident, the post-mortem recommends weekly reporting on the failure category. Six months later, the team produces the report religiously. The same failures continue.",
        "why_it_matters": "Reporting addiction delays action by creating the feeling that something is being done. Documentation is not intervention.",
        "teams_get_wrong": "They confuse producing a report with solving the problem the report describes.",
        "strong_teams": "Every report must answer: who acts on this, what do they do, and by when. If it cannot answer those questions, it is not a report — it is a record.",
        "related_terms": ["metric-theater", "dashboard-sedation", "vanity-signal"],
        "keywords": ["too many reports", "reporting overhead", "report fatigue"],
    },
    {
        "slug": "threshold-drift",
        "name": "Threshold Drift",
        "pos": "n.",
        "definition": "When alert thresholds gradually loosen until they no longer catch real problems.",
        "category": "dashboard-failure",
        "explanation": "Teams set thresholds. Alerts fire too often. They loosen the threshold. Repeat. Eventually the threshold is so loose it only catches catastrophic failures — missing everything in between.",
        "example": "A fraud alert originally fires at 100 dollars. Too many false positives. Raised to 500. Then 1000. Then 5000. Now it only catches the largest fraud events. Everything under 5000 goes undetected.",
        "why_it_matters": "Threshold drift is invisible. Nobody decides to stop catching fraud. It happens one adjustment at a time.",
        "teams_get_wrong": "They adjust thresholds to reduce noise without measuring what they stop catching.",
        "strong_teams": "Track what falls below threshold after every adjustment. Measure the cost of what you stop detecting.",
        "related_terms": ["dashboard-sedation", "alert-fatigue", "vanity-signal"],
        "keywords": ["alert threshold", "false positive management", "detection gap"],
    },
    # === Risk Intelligence (5) ===
    {
        "slug": "intelligence-theater",
        "name": "Intelligence Theater",
        "pos": "n.",
        "definition": "Calling a report intelligence without connecting it to a decision or an owner.",
        "category": "risk-intelligence",
        "explanation": "Teams rebrand their reporting function as intelligence without changing what they produce. The output still explains the past. Nobody acts on it differently.",
        "example": "A risk team renames their weekly report to Weekly Intelligence Brief. Same content. Same recipients. Same zero follow-up actions.",
        "why_it_matters": "Calling reporting intelligence sets false expectations. Leadership thinks they have actionable insight. They have a PDF.",
        "teams_get_wrong": "They rename the output without redesigning the process that produces it.",
        "strong_teams": "Intelligence has a recipient, a decision, and a deadline. If it does not trigger action within 24 hours, it is reporting.",
        "related_terms": ["metric-theater", "reporting-addiction", "dashboard-sedation"],
        "keywords": ["business intelligence failure", "reporting vs intelligence", "actionable intelligence"],
    },
    {
        "slug": "alert-fatigue",
        "name": "Alert Fatigue",
        "pos": "n.",
        "definition": "When too many alerts train people to ignore all of them — including the real ones.",
        "category": "risk-intelligence",
        "explanation": "Every false positive teaches the team that alerts do not matter. After enough false positives, the team stops responding. The real alert arrives and gets the same treatment: ignored.",
        "example": "A security team receives 400 alerts per day. They investigate 20. The breach comes through alert number 387 — marked low priority by a rule nobody has reviewed in two years.",
        "why_it_matters": "Alert fatigue is not a technology problem. It is a signal-to-noise problem that erodes human judgment over time.",
        "teams_get_wrong": "They add more alerts thinking more coverage means more safety. It means more noise.",
        "strong_teams": "Fewer alerts, higher confidence. Every alert must have an owner and a response time. Unowned alerts get deleted.",
        "related_terms": ["threshold-drift", "escalation-debt", "intelligence-theater"],
        "keywords": ["alert fatigue", "too many alerts", "false positive problem"],
    },
    {
        "slug": "signal-orphan",
        "name": "Signal Orphan",
        "pos": "n.",
        "definition": "A risk signal that exists in the system but has no owner, no path, and no response plan.",
        "category": "risk-intelligence",
        "explanation": "The signal was built. The dashboard shows it. But nobody was assigned to watch it, nobody defined what to do when it fires, and nobody is accountable for the outcome.",
        "example": "A churn prediction model outputs a daily list of at-risk accounts. The list goes to a shared folder. No team owns it. No SLA exists. Accounts churn while the signal sits unread.",
        "why_it_matters": "Signal orphans create liability. The organization can detect the problem but cannot prove it tried to act.",
        "teams_get_wrong": "They build signals without building response systems. Detection without action is documentation of failure.",
        "strong_teams": "Every signal has an owner, a threshold, a response time, and an escalation path. No orphans allowed.",
        "related_terms": ["escalation-debt", "alert-fatigue", "intelligence-theater"],
        "keywords": ["unowned alerts", "risk signal ownership", "detection without action"],
    },
    {
        "slug": "retrospective-intelligence",
        "name": "Retrospective Intelligence",
        "pos": "n.",
        "definition": "Analysis that arrives after the decision window has closed.",
        "category": "risk-intelligence",
        "explanation": "The insight is correct. The timing is wrong. By the time the analysis reaches the decision-maker, the opportunity to act has passed. It becomes a post-mortem, not a pre-mortem.",
        "example": "A weekly fraud report identifies a new attack pattern. By the time the report is reviewed on Monday, the attackers have moved on. The pattern was active Tuesday through Friday.",
        "why_it_matters": "Late intelligence is not intelligence. It is history. The value of a signal degrades with every hour of delay.",
        "teams_get_wrong": "They produce intelligence on a calendar schedule instead of an event-driven schedule.",
        "strong_teams": "Match intelligence delivery to decision speed. If the threat moves in hours, the intelligence must arrive in minutes.",
        "related_terms": ["decision-latency", "signal-orphan", "alert-fatigue"],
        "keywords": ["late intelligence", "delayed analysis", "time-sensitive decisions"],
    },
    {
        "slug": "context-collapse",
        "name": "Context Collapse",
        "pos": "n.",
        "definition": "When a metric loses its meaning because the context that made it useful has changed.",
        "category": "risk-intelligence",
        "explanation": "A metric was defined in one context. The business changed. The metric stayed. Now it measures something that no longer matters — but nobody updated the definition or the threshold.",
        "example": "A call center tracks average handle time. The metric was set when calls were simple billing questions. Now calls involve complex technical troubleshooting. The old target punishes agents for doing their job well.",
        "why_it_matters": "Context collapse turns good metrics into harmful ones. Teams optimize for outdated targets and damage current operations.",
        "teams_get_wrong": "They inherit metrics without questioning whether the original context still applies.",
        "strong_teams": "Review every metric annually. Ask: does this still measure what we think it measures? Has the business changed around it?",
        "related_terms": ["threshold-drift", "metric-theater", "vanity-signal"],
        "keywords": ["outdated metrics", "metric context", "KPI relevance"],
    },
    # === Automation Failure (5) ===
    {
        "slug": "automation-fog",
        "name": "Automation Fog",
        "pos": "n.",
        "definition": "The loss of operational visibility when automated systems handle work nobody understands anymore.",
        "category": "automation-failure",
        "explanation": "When processes are automated, the humans who understood them leave or forget. When automation breaks, nobody knows what it was doing, why, or how to fix it.",
        "example": "An insurance company automates claims routing. Two years later, the rules engine routes 15 percent of claims to a dead queue. Nobody notices because nobody monitors the logic.",
        "why_it_matters": "Automation fog turns small failures into invisible ones. By the time someone notices, the damage is systemic.",
        "teams_get_wrong": "They automate and walk away. They measure output without monitoring the logic.",
        "strong_teams": "Maintain documentation for every automated process. Assign an owner who reviews logic quarterly. Build alerts for silent failures.",
        "related_terms": ["ai-theater", "escalation-debt", "the-fluent-fallacy"],
        "keywords": ["automation failure", "automated process risk", "invisible automation errors"],
    },
    {
        "slug": "silent-failure",
        "name": "Silent Failure",
        "pos": "n.",
        "definition": "When an automated system fails without generating any alert or visible error.",
        "category": "automation-failure",
        "explanation": "The system does not crash. It does not throw an error. It simply stops doing what it should — or does it wrong — and nobody notices because no monitoring exists for that specific behavior.",
        "example": "An email automation stops sending renewal reminders due to a config change. No error. No alert. Renewals drop 30 percent over two months before anyone connects the dots.",
        "why_it_matters": "Silent failures are the most expensive kind. They compound daily without detection until the cumulative damage forces discovery.",
        "teams_get_wrong": "They only monitor for crashes and errors. They do not monitor for absence of expected behavior.",
        "strong_teams": "Monitor for what should happen, not just what should not. If the system should send 100 emails daily and sends 0, that is a failure.",
        "related_terms": ["automation-fog", "threshold-drift", "signal-orphan"],
        "keywords": ["silent system failure", "undetected errors", "monitoring gaps"],
    },
    {
        "slug": "complexity-debt",
        "name": "Complexity Debt",
        "pos": "n.",
        "definition": "The hidden cost of automation layers that nobody can fully explain or safely modify.",
        "category": "automation-failure",
        "explanation": "Each automation adds a layer. Each layer interacts with others. Eventually the system is so complex that changing one rule risks breaking five others. Nobody touches it. It becomes untouchable legacy.",
        "example": "A pricing engine has 400 rules built over 5 years by 12 different people. Nobody knows which rules conflict. Changing one price tier requires a two-week impact analysis.",
        "why_it_matters": "Complexity debt slows innovation. Teams cannot move fast because they cannot predict what breaks.",
        "teams_get_wrong": "They add rules without removing old ones. They never simplify.",
        "strong_teams": "Enforce a rule budget. For every new rule added, one must be retired. Document dependencies explicitly.",
        "related_terms": ["automation-fog", "silent-failure", "governance-fog"],
        "keywords": ["system complexity", "technical debt", "automation complexity"],
    },
    {
        "slug": "human-bypass",
        "name": "Human Bypass",
        "pos": "n.",
        "definition": "When people create workarounds to avoid an automated system they do not trust.",
        "category": "automation-failure",
        "explanation": "The automation exists. People do not use it. They email instead of using the ticket system. They call instead of using the chatbot. They export to Excel instead of using the dashboard.",
        "example": "A company deploys an AI-powered support chatbot. Agents tell customers to email directly because the chatbot gives wrong answers. The chatbot reports 95 percent resolution. Reality is 40 percent.",
        "why_it_matters": "Human bypass means the automation metrics are lying. The system reports success while humans do the actual work in shadow processes.",
        "teams_get_wrong": "They trust automation metrics without checking whether humans are actually using the system.",
        "strong_teams": "Measure adoption, not just availability. If people bypass the system, fix the system — do not force compliance.",
        "related_terms": ["automation-fog", "silent-failure", "the-fluent-fallacy"],
        "keywords": ["automation adoption", "system workarounds", "shadow processes"],
    },
    {
        "slug": "model-worship",
        "name": "Model Worship",
        "pos": "n.",
        "definition": "Treating an AI model's output as truth because the model is complex and expensive.",
        "category": "automation-failure",
        "explanation": "The more sophisticated and expensive the model, the less people question it. Complexity becomes authority. Cost becomes credibility. Neither is a valid reason to trust output.",
        "example": "A company spends 2 million on a demand forecasting model. The model predicts a 40 percent demand spike. Nobody questions it because of the investment. They over-order. Demand is flat.",
        "why_it_matters": "Model worship removes healthy skepticism from decision-making. The model becomes unquestionable — which is exactly when it becomes dangerous.",
        "teams_get_wrong": "They treat model confidence as certainty. They do not maintain human override authority.",
        "strong_teams": "Every model output is a suggestion, not a decision. Human judgment remains the final authority. Cost of the model does not equal accuracy of the model.",
        "related_terms": ["the-fluent-fallacy", "ai-theater", "automation-fog"],
        "keywords": ["AI model trust", "model overconfidence", "AI decision authority"],
    },
    # === AI Job Risk (5) ===
    {
        "slug": "tool-operator-trap",
        "name": "Tool Operator Trap",
        "pos": "n.",
        "definition": "Building a career around operating a tool that AI will soon operate better.",
        "category": "ai-job-risk",
        "explanation": "The professional's value comes from knowing how to use a specific tool — not from the judgment that follows. When AI learns the tool, the operator has nothing left to offer.",
        "example": "An analyst builds their career around advanced Excel modeling. AI tools now generate the same models from a text prompt. The analyst's 10 years of Excel expertise becomes a commodity overnight.",
        "why_it_matters": "Tool operators are the most exposed category in the AI era. Their skills are precisely what AI replicates first.",
        "teams_get_wrong": "They reward tool proficiency instead of decision quality. They promote the fastest operator, not the best thinker.",
        "strong_teams": "Evaluate people on decisions influenced, not reports produced. Invest in judgment development, not tool training.",
        "related_terms": ["credential-erosion", "output-identity", "busy-work-collapse"],
        "keywords": ["AI replacing tool operators", "skill obsolescence", "AI job exposure"],
    },
    {
        "slug": "credential-erosion",
        "name": "Credential Erosion",
        "pos": "n.",
        "definition": "When qualifications that once guaranteed employment lose value because AI handles what they certified.",
        "category": "ai-job-risk",
        "explanation": "Degrees and certifications were proxies for capability. AI makes the capability directly available without the credential. The proxy loses its value.",
        "example": "A data analytics certification guaranteed you could build dashboards and run queries. AI tools now do both from natural language. The certification still exists. The job it qualified you for does not.",
        "why_it_matters": "Credential erosion affects hiring, career planning, and education investment. People invest years in qualifications that depreciate faster than expected.",
        "teams_get_wrong": "They hire based on credentials instead of demonstrated judgment. They require degrees for roles that AI has already simplified.",
        "strong_teams": "Hire for judgment, adaptability, and decision quality. Treat credentials as context, not qualification.",
        "related_terms": ["tool-operator-trap", "output-identity", "busy-work-collapse"],
        "keywords": ["degrees losing value", "credential obsolescence", "AI and education"],
    },
    {
        "slug": "output-identity",
        "name": "Output Identity",
        "pos": "n.",
        "definition": "When a professional's sense of value is tied to producing outputs that AI now produces faster.",
        "category": "ai-job-risk",
        "explanation": "The person defines themselves by what they produce: reports, analyses, summaries, presentations. When AI produces the same outputs in seconds, the person faces an identity crisis — not just a job crisis.",
        "example": "A senior analyst takes pride in their weekly 30-page market report. AI generates a better version in 2 minutes. The analyst's identity — not just their task — is threatened.",
        "why_it_matters": "Output identity makes people resist AI adoption. They fight the tool that threatens their self-worth, even when it would make them more effective.",
        "teams_get_wrong": "They do not help people transition their identity from output producer to decision shaper.",
        "strong_teams": "Redefine value around outcomes and decisions, not outputs. Help people see AI as leverage, not replacement.",
        "related_terms": ["tool-operator-trap", "credential-erosion", "busy-work-collapse"],
        "keywords": ["AI identity crisis", "professional identity", "AI career transition"],
    },
    {
        "slug": "busy-work-collapse",
        "name": "Busy Work Collapse",
        "pos": "n.",
        "definition": "When AI eliminates the routine tasks that filled 80 percent of a role, exposing that the remaining 20 percent was the only real value.",
        "category": "ai-job-risk",
        "explanation": "Most knowledge workers spend the majority of their time on tasks AI can handle: formatting, summarizing, routing, scheduling. When that work disappears, what remains reveals the true value — or lack of it.",
        "example": "A project coordinator spends 80 percent of their time on status updates, meeting scheduling, and report formatting. AI handles all of it. The remaining 20 percent — stakeholder negotiation and risk judgment — is what the role was always supposed to be.",
        "why_it_matters": "Busy work collapse is not future. It is happening now. Professionals who cannot articulate their judgment value are already exposed.",
        "teams_get_wrong": "They try to protect busy work instead of accelerating the transition to judgment work.",
        "strong_teams": "Audit every role at the task level. Identify the 20 percent that requires human judgment. Build the role around that.",
        "related_terms": ["tool-operator-trap", "output-identity", "credential-erosion"],
        "keywords": ["AI eliminating tasks", "busy work automation", "knowledge work exposure"],
    },
    {
        "slug": "ai-safety-theater",
        "name": "AI Safety Theater",
        "pos": "n.",
        "definition": "Generic career advice that gives professionals false comfort about their AI exposure.",
        "category": "ai-job-risk",
        "explanation": "Just learn prompt engineering. Soft skills will save you. Creativity is safe. These claims comfort without informing. They do not specify which tasks are exposed or what to do this month.",
        "example": "A career coach tells a data analyst to focus on creativity and communication. The analyst feels reassured. Six months later, their reporting role is automated. Creativity did not help because the role never required it.",
        "why_it_matters": "AI safety theater delays necessary career transitions by providing false comfort. People stop adapting because they believe they are already safe.",
        "teams_get_wrong": "They share generic AI career advice without role-specific task analysis.",
        "strong_teams": "Provide specific, task-level exposure assessments. Show people exactly which parts of their role are at risk and what to build instead.",
        "related_terms": ["tool-operator-trap", "credential-erosion", "the-fluent-fallacy"],
        "keywords": ["AI career advice", "AI proof career myth", "false AI safety"],
    },
    # === Leadership Under Pressure (5) ===
    {
        "slug": "meeting-paralysis",
        "name": "Meeting Paralysis",
        "pos": "n.",
        "definition": "When decisions cannot happen without a meeting, and meetings cannot happen fast enough.",
        "category": "leadership-under-pressure",
        "explanation": "The organization requires consensus before action. Consensus requires a meeting. Meetings require calendars. Calendars require days. The threat does not wait for your calendar.",
        "example": "A security incident is detected at 3pm Friday. The response requires cross-team coordination. The earliest available meeting slot is Tuesday. The attacker has the weekend.",
        "why_it_matters": "Meeting paralysis turns fast-moving threats into slow-moving disasters. It is the organizational equivalent of a slow internet connection during a crisis.",
        "teams_get_wrong": "They require meetings for decisions that should be pre-authorized.",
        "strong_teams": "Pre-commit decision rights for known scenarios. Reserve meetings for novel situations only.",
        "related_terms": ["decision-latency", "escalation-debt", "governance-fog"],
        "keywords": ["meeting culture", "decision speed", "organizational paralysis"],
    },
    {
        "slug": "accountability-diffusion",
        "name": "Accountability Diffusion",
        "pos": "n.",
        "definition": "When everyone is responsible for a decision, nobody is accountable for the outcome.",
        "category": "leadership-under-pressure",
        "explanation": "Shared ownership sounds collaborative. In practice, it means nobody owns the failure. When things go wrong, everyone points to the group decision. Nobody signed their name.",
        "example": "A cross-functional team decides to delay a security patch. The decision is made by committee. When the breach happens, nobody is accountable. The committee cannot be fired.",
        "why_it_matters": "Accountability diffusion removes consequences from bad decisions. Without consequences, decision quality degrades.",
        "teams_get_wrong": "They distribute ownership to reduce individual risk. They create committees instead of owners.",
        "strong_teams": "One name per decision. The person who approves owns the outcome. Committees advise. Individuals decide.",
        "related_terms": ["meeting-paralysis", "governance-fog", "escalation-debt"],
        "keywords": ["shared accountability", "decision ownership", "committee decisions"],
    },
    {
        "slug": "comfort-metrics",
        "name": "Comfort Metrics",
        "pos": "n.",
        "definition": "Metrics chosen because they make leadership feel good, not because they drive action.",
        "category": "leadership-under-pressure",
        "explanation": "Leadership asks for metrics that confirm progress. Teams deliver metrics that show green. Nobody asks whether green means safe or just means the bar is low enough.",
        "example": "A CEO asks for an AI adoption scorecard. The team reports 12 AI projects in progress. The CEO feels good. None of the 12 projects have changed a single operational decision.",
        "why_it_matters": "Comfort metrics create false confidence at the leadership level. They prevent hard conversations about real performance.",
        "teams_get_wrong": "They give leadership what they want to hear instead of what they need to know.",
        "strong_teams": "Report uncomfortable truths. Include at least one metric per report that makes someone nervous.",
        "related_terms": ["dashboard-sedation", "metric-theater", "vanity-signal"],
        "keywords": ["leadership metrics", "false confidence", "executive reporting"],
    },
    {
        "slug": "delegation-theater",
        "name": "Delegation Theater",
        "pos": "n.",
        "definition": "Assigning ownership without granting the authority needed to act.",
        "category": "leadership-under-pressure",
        "explanation": "A leader delegates a problem to a team. The team has responsibility but no budget, no authority to change processes, and no mandate to override other teams. They own the problem on paper. They cannot solve it in practice.",
        "example": "A VP assigns AI risk management to a junior analyst. The analyst has no budget, no authority over engineering, and no access to leadership. They produce reports. Nothing changes.",
        "why_it_matters": "Delegation theater creates the appearance of action while ensuring nothing actually changes. It protects leadership from accountability.",
        "teams_get_wrong": "They accept delegated responsibility without negotiating for authority.",
        "strong_teams": "Delegation includes authority, budget, and access. If you own the problem, you must be able to solve it.",
        "related_terms": ["accountability-diffusion", "meeting-paralysis", "governance-fog"],
        "keywords": ["delegation failure", "responsibility without authority", "leadership accountability"],
    },
    {
        "slug": "crisis-amnesia",
        "name": "Crisis Amnesia",
        "pos": "n.",
        "definition": "The organizational tendency to forget lessons from the last crisis within weeks of resolving it.",
        "category": "leadership-under-pressure",
        "explanation": "During a crisis, everyone agrees things must change. Post-mortems are written. Action items are assigned. Within 6 weeks, urgency fades. The action items stall. The next crisis finds the same gaps.",
        "example": "After a major data breach, the company commits to weekly security reviews. By month three, the reviews are monthly. By month six, they are quarterly. By month nine, they are cancelled.",
        "why_it_matters": "Crisis amnesia means organizations pay for the same failure repeatedly. Each crisis feels new because the lessons from the last one were never institutionalized.",
        "teams_get_wrong": "They treat post-mortems as closure instead of commitment. They archive lessons instead of implementing them.",
        "strong_teams": "Assign post-mortem actions to named owners with deadlines. Review completion monthly. Never archive without implementation.",
        "related_terms": ["escalation-debt", "accountability-diffusion", "meeting-paralysis"],
        "keywords": ["organizational learning", "post-mortem failure", "crisis response"],
    },
    # === Fraud and Risk Signals (5) ===
    {
        "slug": "pattern-blindness",
        "name": "Pattern Blindness",
        "pos": "n.",
        "definition": "When familiarity with normal operations prevents teams from seeing abnormal patterns.",
        "category": "fraud-and-risk-signals",
        "explanation": "Teams see the same data every day. Anomalies that would alarm a newcomer are invisible to veterans because they have normalized the abnormal over time.",
        "example": "A payments team processes 10000 transactions daily. A new fraud pattern emerges gradually — 50 extra transactions per day. Nobody notices because the daily volume looks normal. After 6 months, 9000 fraudulent transactions have passed.",
        "why_it_matters": "Pattern blindness is the enemy of detection. The longer you watch something, the less you see changes in it.",
        "teams_get_wrong": "They rely on experienced operators to spot anomalies. Experience creates blindness, not vigilance.",
        "strong_teams": "Rotate analysts across domains. Use statistical anomaly detection that does not normalize. Bring fresh eyes quarterly.",
        "related_terms": ["threshold-drift", "silent-failure", "context-collapse"],
        "keywords": ["fraud detection failure", "anomaly blindness", "pattern recognition"],
    },
    {
        "slug": "false-negative-comfort",
        "name": "False Negative Comfort",
        "pos": "n.",
        "definition": "The dangerous assumption that absence of alerts means absence of problems.",
        "category": "fraud-and-risk-signals",
        "explanation": "No alerts fired today. The team relaxes. But the absence of alerts might mean the detection system is broken, the thresholds are wrong, or the attacker is operating below the radar.",
        "example": "A fraud team celebrates a quiet month — zero alerts. Investigation reveals the detection model was silently failing for 3 weeks due to a data pipeline change. Fraud was happening. Detection was not.",
        "why_it_matters": "False negative comfort is more dangerous than false positive fatigue. At least false positives prove the system is watching.",
        "teams_get_wrong": "They treat quiet periods as success instead of investigating why it is quiet.",
        "strong_teams": "Monitor for expected alert volume. If alerts drop below baseline, investigate immediately. Silence is suspicious.",
        "related_terms": ["silent-failure", "pattern-blindness", "threshold-drift"],
        "keywords": ["false negatives", "detection gaps", "fraud monitoring"],
    },
    {
        "slug": "investigation-theater",
        "name": "Investigation Theater",
        "pos": "n.",
        "definition": "Going through the motions of investigating without the authority or intent to act on findings.",
        "category": "fraud-and-risk-signals",
        "explanation": "The investigation happens. The report is written. The findings are clear. But nobody has the authority to implement the recommendations. The investigation exists for compliance, not for change.",
        "example": "An internal audit identifies a control gap that enabled 2 million in fraud. The report recommends system changes. The recommendation sits in a backlog for 18 months. The same gap enables another loss.",
        "why_it_matters": "Investigation theater satisfies regulators while failing the business. It documents problems without solving them.",
        "teams_get_wrong": "They measure investigations completed instead of recommendations implemented.",
        "strong_teams": "Every investigation has an implementation owner and a deadline. Findings without action are just expensive documentation.",
        "related_terms": ["escalation-debt", "accountability-diffusion", "crisis-amnesia"],
        "keywords": ["investigation failure", "audit recommendations", "compliance theater"],
    },
    {
        "slug": "velocity-blindness",
        "name": "Velocity Blindness",
        "pos": "n.",
        "definition": "Failing to detect threats because the detection system cannot match the speed of the attack.",
        "category": "fraud-and-risk-signals",
        "explanation": "The attack moves in minutes. The detection runs hourly. By the time the system catches up, the damage is done. Speed mismatch is a design failure, not a technology failure.",
        "example": "Account takeover attacks complete in under 90 seconds. The fraud detection batch job runs every 4 hours. Every attack succeeds before detection even begins.",
        "why_it_matters": "Velocity blindness means your detection is always retrospective. You document losses instead of preventing them.",
        "teams_get_wrong": "They build detection for the speed of their reporting cycle, not the speed of the threat.",
        "strong_teams": "Match detection speed to threat speed. If the attack takes seconds, detection must take seconds.",
        "related_terms": ["decision-latency", "pattern-blindness", "false-negative-comfort"],
        "keywords": ["real-time detection", "fraud speed", "detection latency"],
    },
    {
        "slug": "control-decay",
        "name": "Control Decay",
        "pos": "n.",
        "definition": "The gradual weakening of risk controls as the organization grows and changes around them.",
        "category": "fraud-and-risk-signals",
        "explanation": "Controls are designed for a specific context. The business grows. New products launch. New channels open. The controls stay the same. Gaps appear where new activity meets old rules.",
        "example": "A payment fraud control was designed for card-present transactions. The company launches an online channel. The control does not cover card-not-present. Online fraud grows unchecked for a year.",
        "why_it_matters": "Control decay is invisible until a loss event reveals the gap. By then, the gap has been exploitable for months or years.",
        "teams_get_wrong": "They set controls and forget them. They do not review controls when the business changes.",
        "strong_teams": "Review controls every time a new product, channel, or process launches. Map controls to current risk, not historical risk.",
        "related_terms": ["threshold-drift", "pattern-blindness", "silent-failure"],
        "keywords": ["control effectiveness", "risk control gaps", "control review"],
    },
]

# Generate .md files
os.makedirs("lexicon", exist_ok=True)
today = "2026-05-31"
count = 0

for term in TERMS:
    slug = term["slug"]
    related_yaml = "\n".join([f'  - "{rt}"' for rt in term.get("related_terms", [])])
    keywords_yaml = "\n".join([f'  - "{kw}"' for kw in term.get("keywords", [])])

    def esc(s):
        return s.replace('"', '\\"') if s else ""

    content = f'''---
layout: lexicon-term
title: "{esc(term['name'])} — AI Operations Lexicon"
share-title: "{esc(term['name'])} — AI Operations Lexicon"
share-description: "{esc(term['definition'])}"
permalink: /lexicon/{slug}/
term_name: "{esc(term['name'])}"
pos: "{term['pos']}"
definition: "{esc(term['definition'])}"
category: "{term['category']}"
explanation: "{esc(term['explanation'])}"
example: "{esc(term['example'])}"
why_it_matters: "{esc(term['why_it_matters'])}"
teams_get_wrong: "{esc(term['teams_get_wrong'])}"
strong_teams: "{esc(term['strong_teams'])}"
related_terms:
{related_yaml}
keywords:
{keywords_yaml}
updated_at: "{today}"
---
'''
    with open(f"lexicon/{slug}.md", "w") as f:
        f.write(content)
    count += 1

print(f"Created {count} lexicon term pages")
